package ventanas;

import herramientas.LimpiarString;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import main.Ciudad;
import main.Lienzo;

public class AgregarCiudad extends javax.swing.JFrame {

    private Lienzo lienzo;

    public AgregarCiudad(Lienzo lienzo) {
        initComponents();
        this.lienzo = lienzo;
        this.setLocationRelativeTo(null);
        initMoreConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCiudad = new javax.swing.JTextField();
        btnAgregarCiudad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        selectorCiudadAdy1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        selectorCiudadAdy2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDistanciaCiudad1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDistanciaCiudad2 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Agrega una Nueva Ciudad");

        jLabel2.setText("Nombre de la ciudad:");

        btnAgregarCiudad.setText("Enviar Ciudad");
        btnAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCiudadActionPerformed(evt);
            }
        });

        jLabel3.setText("Ciudad Adyecente 1");

        jLabel5.setText("Ciudad Adyecente 2");

        jLabel4.setText("Distancia Hacia Ciudad Adyecente 1");

        txtDistanciaCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanciaCiudad1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Distancia Hacia Ciudad Adyecente 2");

        txtDistanciaCiudad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanciaCiudad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCiudad)
                    .addComponent(btnAgregarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorCiudadAdy1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorCiudadAdy2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDistanciaCiudad1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDistanciaCiudad2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectorCiudadAdy1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDistanciaCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectorCiudadAdy2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDistanciaCiudad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCiudadActionPerformed

        if (this.txtNombreCiudad.equals("") || this.txtDistanciaCiudad1.equals("") || this.txtDistanciaCiudad2.equals("")
                || (this.selectorCiudadAdy1.getSelectedIndex() == this.selectorCiudadAdy2.getSelectedIndex()) 
                || (this.selectorCiudadAdy2.getSelectedIndex() == this.selectorCiudadAdy1.getSelectedIndex()))  {
            JOptionPane.showMessageDialog(null, "Completar todos los campos.\n "
                    + "Las ciudades adyacentes deben de ser distintas.");
        } else {
            
            int idCiudad = lienzo.getCiudades().size() - 1;
            Ciudad city = new Ciudad(idCiudad, this.txtNombreCiudad.getText());
            lienzo.getCiudades().add(city);
            
            lienzo.getGraph().cargarNuevaCiudad(lienzo.getCiudades().size(), lienzo.getGraph().getGraphEstructura());
            
            this.setVisible(false);            
        }
        
    }//GEN-LAST:event_btnAgregarCiudadActionPerformed

    private void txtDistanciaCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanciaCiudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistanciaCiudad1ActionPerformed

    private void txtDistanciaCiudad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanciaCiudad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistanciaCiudad2ActionPerformed

    /**
     * Inicia los valores de variables extras del sistema
     */
    private void initMoreConfig() {

        for (Ciudad c : lienzo.getCiudades()) {
            String txt = "Id: " + c.getId() + ", " + c.getNombre();
            this.selectorCiudadAdy1.addItem(txt);
            this.selectorCiudadAdy2.addItem(txt);
        }

        this.selectorCiudadAdy2.setSelectedIndex(1);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectorCiudadAdy1;
    private javax.swing.JComboBox<String> selectorCiudadAdy2;
    private javax.swing.JTextField txtDistanciaCiudad1;
    private javax.swing.JTextField txtDistanciaCiudad2;
    private javax.swing.JTextField txtNombreCiudad;
    // End of variables declaration//GEN-END:variables

}
