/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Graphics;
import javax.swing.JFrame;
import javax.swing.JPanel;
import main.Lienzo;

/**
 *
 * @author nleal
 */
public class Principal extends javax.swing.JFrame {

    private Lienzo lienzo;

    public Principal(Lienzo lienzo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.lienzo = lienzo;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarCiudad = new javax.swing.JButton();
        btnCargarArchivo = new javax.swing.JButton();
        btnDibujarGrafo = new javax.swing.JButton();
        btnSimulacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traveling Salesman Problem");
        setName("v_principal"); // NOI18N

        btnAgregarCiudad.setText("Agregar Ciudad");
        btnAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCiudadActionPerformed(evt);
            }
        });

        btnCargarArchivo.setText("Cargar Archivo");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        btnDibujarGrafo.setText("Dibujar Simulacion");
        btnDibujarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDibujarGrafoActionPerformed(evt);
            }
        });

        btnSimulacion.setText("Crear Simulacion");
        btnSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDibujarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDibujarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * BOTON PARA AGREGAR NUEVA CIUDAD
     * @param evt 
     */
    private void btnAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCiudadActionPerformed
        AgregarCiudad agregar = new AgregarCiudad(lienzo);
        agregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarCiudadActionPerformed

    /**
     * BOTON PARA CARGAR NUEVO ARCHIVO
     * @param evt 
     */
    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        
        CargarArchivo cargar = new CargarArchivo(lienzo);
        cargar.setVisible(true);
        
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    /**
     * BOTON PARA DIBUJAR EL GRAFO
     * @param evt 
     */
    private void btnDibujarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDibujarGrafoActionPerformed
        
        JFrame f = new JFrame("Grafos");
        f.setSize(1280, 720);
        f.add(lienzo);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        f.setVisible(true);
        
    }//GEN-LAST:event_btnDibujarGrafoActionPerformed

    /**
     * BOTON PARA INICIAR UNA NUEVA SIMULACION
     * @param evt 
     */
    private void btnSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulacionActionPerformed
        Simulacion s = new Simulacion(lienzo);
        s.setVisible(true);
    }//GEN-LAST:event_btnSimulacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCiudad;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnDibujarGrafo;
    private javax.swing.JButton btnSimulacion;
    // End of variables declaration//GEN-END:variables
}
